[build]
  base = "client"
  command = "CI=false npm install && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# React SPA routing fix - sab routes index.html pe redirect honge
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

