[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# React SPA routing fix - sab routes index.html pe redirect honge
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

